config/routes.rb
Rails.application.routes.draw do
  resources :ateliers
  resources :salles
  get 'welcome/index'

  root 'welcome#index'

end

app/models/atelier.rb
class Atelier < ActiveRecord::Base
  belongs_to :salle

  validates :presente_par, :titre, :salle_id, :heure_debut, :heure_fin,
      presence: true

  validate :validation_heure_fin

  validate :disponibilite, unless: 'salle.nil?'

  def validation_heure_fin
    errors.add(:heure_fin, "doit être supérieure à l'heure de début") if heure_fin <= heure_debut

    errors[:base] << 'la présentation doit faire au moins 30 minutes' if heure_fin - heure_debut < 30.minutes
  end

  def disponibilite
    if Atelier.exists?(['heure_debut < ? and heure_fin > ?', self.heure_debut, self.heure_debut]) or
        Atelier.exists?(['heure_debut > ? and heure_fin < ?', self.heure_debut, self.heure_fin]) or
        Atelier.exists?(['heure_debut < ? and heure_fin > ?', self.heure_fin, self.heure_fin])
      errors[:base] << "'#{salle.nom}' ne sera pas disponible à cette heure"
    end
  end
end

app/models/salle.rb
class Salle < ActiveRecord::Base
  validates :nom, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ateliers_controller.rb
class AteliersController < ApplicationController
  before_action :set_atelier, only: [:show, :edit, :update, :destroy]

  # GET /ateliers
  # GET /ateliers.json
  def index
    @ateliers = Atelier.all
  end

  # GET /ateliers/1
  # GET /ateliers/1.json
  def show
  end

  # GET /ateliers/new
  def new
    @atelier = Atelier.new
  end

  # GET /ateliers/1/edit
  def edit
  end

  # POST /ateliers
  # POST /ateliers.json
  def create
    @atelier = Atelier.new(atelier_params)

    respond_to do |format|
      if @atelier.save
        format.html { redirect_to @atelier, notice: 'Atelier was successfully created.' }
        format.json { render :show, status: :created, location: @atelier }
      else
        format.html { render :new }
        format.json { render json: @atelier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ateliers/1
  # PATCH/PUT /ateliers/1.json
  def update
    respond_to do |format|
      if @atelier.update(atelier_params)
        format.html { redirect_to @atelier, notice: 'Atelier was successfully updated.' }
        format.json { render :show, status: :ok, location: @atelier }
      else
        format.html { render :edit }
        format.json { render json: @atelier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ateliers/1
  # DELETE /ateliers/1.json
  def destroy
    @atelier.destroy
    respond_to do |format|
      format.html { redirect_to ateliers_url, notice: 'Atelier was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_atelier
      @atelier = Atelier.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def atelier_params
      params.require(:atelier).permit(:titre, :presente_par, :entreprise, :salle_id, :heure_debut, :heure_fin)
    end
end

app/controllers/salles_controller.rb
class SallesController < ApplicationController
  before_action :set_salle, only: [:show, :edit, :update, :destroy]

  # GET /salles
  # GET /salles.json
  def index
    @salles = Salle.all
  end

  # GET /salles/1
  # GET /salles/1.json
  def show
  end

  # GET /salles/new
  def new
    @salle = Salle.new
  end

  # GET /salles/1/edit
  def edit
  end

  # POST /salles
  # POST /salles.json
  def create
    @salle = Salle.new(salle_params)

    respond_to do |format|
      if @salle.save
        format.html { redirect_to @salle, notice: 'Salle was successfully created.' }
        format.json { render :show, status: :created, location: @salle }
      else
        format.html { render :new }
        format.json { render json: @salle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /salles/1
  # PATCH/PUT /salles/1.json
  def update
    respond_to do |format|
      if @salle.update(salle_params)
        format.html { redirect_to @salle, notice: 'Salle was successfully updated.' }
        format.json { render :show, status: :ok, location: @salle }
      else
        format.html { render :edit }
        format.json { render json: @salle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /salles/1
  # DELETE /salles/1.json
  def destroy
    @salle.destroy
    respond_to do |format|
      format.html { redirect_to salles_url, notice: 'Salle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_salle
      @salle = Salle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def salle_params
      params.require(:salle).permit(:nom)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ateliers_helper.rb
module AteliersHelper
end

app/helpers/salles_helper.rb
module SallesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/ateliers/_form.html.erb
<%= form_for @atelier, :html => { :class => "form-horizontal atelier" } do |f| %>

    <% if @atelier.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@atelier.errors.count, "error") %> prohibited this atelier from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
              <% @atelier.errors.full_messages.each do |msg| %>
                  <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
    <% end %>

    <div class="form-group">
      <%= f.label :titre, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :titre, :class => 'form-control' %>
      </div>
      <%=f.error_span(:titre) %>
    </div>
    <div class="form-group">
      <%= f.label :presente_par, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :presente_par, :class => 'form-control' %>
      </div>
      <%=f.error_span(:presente_par) %>
    </div>
    <div class="form-group">
      <%= f.label :entreprise, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.text_field :entreprise, :class => 'form-control' %>
      </div>
      <%=f.error_span(:entreprise) %>
    </div>
    <div class="form-group">
      <%= f.label :salle_id, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.collection_select :salle_id, Salle.all, :id, :nom, prompt: true %>
      </div>
      <%=f.error_span(:salle_id) %>
    </div>
    <div class="form-group">
      <%= f.label :heure_debut, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.time_select :heure_debut, :class => 'form-control' %>
      </div>
      <%=f.error_span(:heure_debut) %>
    </div>
    <div class="form-group">
      <%= f.label :heure_fin, :class => 'control-label col-lg-2' %>
      <div class="col-lg-10">
        <%= f.time_select :heure_fin, :class => 'form-control' %>
      </div>
      <%=f.error_span(:heure_fin) %>
    </div>

    <div class="form-group">
      <div class="col-lg-offset-2 col-lg-10">
        <%= f.submit nil, :class => 'btn btn-primary' %>
        <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                    ateliers_path, :class => 'btn btn-default' %>
      </div>
    </div>

<% end %>

app/views/ateliers/edit.html.erb
<%- model_class = Atelier -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ateliers/index.html.erb
<%- model_class = Atelier -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:titre) %></th>
      <th><%= model_class.human_attribute_name(:presente_par) %></th>
      <th><%= model_class.human_attribute_name(:entreprise) %></th>
      <th><%= model_class.human_attribute_name(:salle_id) %></th>
      <th><%= model_class.human_attribute_name(:heure_debut) %></th>
      <th><%= model_class.human_attribute_name(:heure_fin) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @ateliers.each do |atelier| %>
      <tr>
        <td><%= link_to atelier.id, atelier_path(atelier) %></td>
        <td><%= atelier.titre %></td>
        <td><%= atelier.presente_par %></td>
        <td><%= atelier.entreprise %></td>
        <td><%= atelier.salle.nom %></td>
        <td><%=l atelier.heure_debut, format: :short %></td>
        <td><%=l atelier.heure_fin, format: :short %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_atelier_path(atelier), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      atelier_path(atelier),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_atelier_path,
            :class => 'btn btn-primary' %>

app/views/ateliers/new.html.erb
<%- model_class = Atelier -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/ateliers/show.html.erb
<%- model_class = Atelier -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:titre) %>:</strong></dt>
  <dd><%= @atelier.titre %></dd>
  <dt><strong><%= model_class.human_attribute_name(:presente_par) %>:</strong></dt>
  <dd><%= @atelier.presente_par %></dd>
  <dt><strong><%= model_class.human_attribute_name(:entreprise) %>:</strong></dt>
  <dd><%= @atelier.entreprise %></dd>
  <dt><strong><%= model_class.human_attribute_name(:salle_id) %>:</strong></dt>
  <dd><%= @atelier.salle.nom %></dd>
  <dt><strong><%= model_class.human_attribute_name(:heure_debut) %>:</strong></dt>
  <dd><%= l @atelier.heure_debut, format: :short %></dd>
  <dt><strong><%= model_class.human_attribute_name(:heure_fin) %>:</strong></dt>
  <dd><%= l @atelier.heure_fin, format: :short %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              ateliers_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_atelier_path(@atelier), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              atelier_path(@atelier),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Codecamp" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'CodeCamp', root_path, class: 'navbar-brand' %>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Salles", salles_path %></li>
            <li><%= link_to "Ateliers", ateliers_path %></li>
            <li><%= link_to "Link3", "/path3"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/salles/_form.html.erb
<%= form_for @salle, :html => { :class => "form-horizontal salle" } do |f| %>

  <% if @salle.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@salle.errors.count, "error") %> prohibited this salle from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @salle.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nom, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :nom, :class => 'form-control' %>
    </div>
    <%=f.error_span(:nom) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                salles_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/salles/edit.html.erb
<%- model_class = Salle -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/salles/index.html.erb
<%- model_class = Salle -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:id) %></th>
    <th><%= model_class.human_attribute_name(:nom) %></th>
    <th><%= model_class.human_attribute_name(:created_at) %></th>
    <th><%=t '.actions', :default => t("helpers.actions") %></th>
  </tr>
  </thead>
  <tbody>
  <% @salles.each do |salle| %>
      <tr>
        <td><%= link_to salle.id, salle_path(salle) %></td>
        <td><%= salle.nom %></td>
        <td><%=l salle.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_salle_path(salle), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      salle_path(salle),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
  <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_salle_path,
            :class => 'btn btn-primary' %>

app/views/salles/new.html.erb
<%- model_class = Salle -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/salles/show.html.erb
<%- model_class = Salle -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nom) %>:</strong></dt>
  <dd><%= @salle.nom %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              salles_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_salle_path(@salle), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              salle_path(@salle),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>


<h3>Hello codecampers !!!</h3>